import { defineConfig, devices } from "@playwright/test";
import { readFileSync } from "node:fs";

// Load .env.test.local (generated by scripts/gen-test-env.mjs) so the dev
// server and the auth setup project talk to the LOCAL Supabase stack, not the
// remote project in .env.local. We set process.env directly; @next/env will not
// override an already-set variable, so the dev server keeps these values.
try {
  for (const line of readFileSync(".env.test.local", "utf8").split("\n")) {
    const m = line.match(/^(\w+)=(.*)$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
} catch {
  // Missing during a bare `playwright test` — `npm run test:e2e` generates it first.
}

// Dedicated port so we never reuse (or collide with) a `npm run dev` that's
// pointed at the remote backend.
const PORT = 3100;
const baseURL = `http://localhost:${PORT}`;

export default defineConfig({
  testDir: "./tests",
  fullyParallel: false,
  workers: 1,
  timeout: 45_000,
  expect: { timeout: 10_000 },
  reporter: [["list"]],
  use: {
    baseURL,
    trace: "retain-on-failure",
  },
  projects: [
    { name: "setup", testMatch: /auth\.setup\.ts/ },
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"], storageState: "tests/.auth/state.json" },
      dependencies: ["setup"],
    },
  ],
  webServer: {
    command: `npm run dev -- --port ${PORT}`,
    url: baseURL,
    reuseExistingServer: false,
    timeout: 120_000,
    env: {
      ...process.env,
      NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL ?? "",
      NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "",
      NEXT_PUBLIC_SITE_URL: baseURL,
    },
  },
});
